app-id: net.froemling.BombSquad
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
command: bombsquad.sh
finish-args:
  - --share=network
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --device=dri
  - --filesystem=host

modules:
  - name: SDL2
    buildsystem: cmake
    builddir: true
    cleanup:
      - /bin
      - /include
      - /lib/pkgconfig
      - /lib/cmake
      - /share
      - '*.a'
    sources:
      - type: git
        url: https://github.com/libsdl-org/SDL
        tag: release-2.0.20

  - name: Python
    sources:
      - type: archive
        url: https://www.python.org/ftp/python/3.13.3/Python-3.13.3.tar.xz
        sha256: 40f868bcbdeb8149a3149580bb9bfd407b3321cd48f0be631af955ac92c0e041
    config-opts:
      - --prefix=${FLATPAK_DEST}
      - --enable-shared
      - --enable-optimizations
      - --with-computed-gotos
      - --with-lto
      - --enable-ipv6
      - --with-system-expat
      - --with-system-ffi
      - --with-system-libmpdec
      - --enable-loadable-sqlite-extensions
      - --without-ensurepip
    cleanup:
      - /bin
      - /include
      - /lib/pkgconfig
      - /share

  - name: BombSquad
    buildsystem: simple
    build-commands:
    - mkdir -p ${FLATPAK_DEST}/bin/BombSquad
    - tar axf BombSquad.tar.gz
    - mv BombSquad_*/* ${FLATPAK_DEST}/bin/BombSquad
    - install -Dm755 bombsquad.sh ${FLATPAK_DEST}/bin/bombsquad.sh
    - install -Dm644 -t ${FLATPAK_DEST}/share/applications/ ${FLATPAK_ID}.desktop
    - install -Dm644 ${FLATPAK_ID}.png ${FLATPAK_DEST}/share/icons/hicolor/512x512/apps/${FLATPAK_ID}.png
    - install -Dm644 net.froemling.BombSquad.appdata.xml /app/share/metainfo/net.froemling.BombSquad.metainfo.xml

    sources:

    - type: file
      dest-filename: BombSquad.tar.gz
      url: https://files.ballistica.net/bombsquad/builds/BombSquad_Linux_x86_64_1.7.48.tar.gz
      sha256: d425ed37342320822585c1d94984bca75f2a3c04964a8230bd6c8b8cb4a3c966

    - type: file
      dest-filename: net.froemling.BombSquad.png
      url: https://files.ballistica.net/bombsquad/promo/BombSquadIcon512.png
      sha256: c950d1b62da2714b1ed1afc42244f7e192be23172c89b6fa3e6eaaca8e45a89a

    - type: file
      path: net.froemling.BombSquad.desktop

    - type: file
      path: net.froemling.BombSquad.appdata.xml

    - type: script
      dest-filename: bombsquad.sh
      commands:
        - cd /app/bin/BombSquad
        - exec ./bombsquad
