name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Python venv
        id: cache-venv
        uses: actions/cache@v4
        env:
          cache-name: cache-python-dependencies
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ env.cache-name }}-${{ hashFiles('config/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-${{ env.cache-name }}-
            ${{ runner.os }}-venv-
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Setup project environment
        run: make env
      - name: Build documentation
        run: make docs
      - name: Upload the build
        uses: actions/upload-pages-artifact@v3
        with:
          name: html_docs
          path: build/docs

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: html_docs
