name: Nightly Build
on:
    # Run everyday at 5:30 UTC
    schedule:
      - cron: '30 5 * * *'
    workflow_dispatch:
    push:

jobs:
    make_flatpak_gui_debug:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Cache Python virtualenv
          id: cache-venv
          uses: actions/cache@v4
          env:
            cache-name: cache-python-dependencies
          with:
            path: .venv # cache the virtualenv directory
            key: ${{ runner.os }}-venv-${{ env.cache-name }}-${{ hashFiles('config/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-venv-${{ env.cache-name }}-
              ${{ runner.os }}-venv-
              ${{ runner.os }}
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'
        - if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
          name: List the state of node modules
          continue-on-error: true
          run: pip list
        - name: Setup project environment
          run: |
            make env
            sudo apt install flatpak flatpak-builder
        - name: Make the build
          run: |
            sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
            echo "remote added"
            sudo flatpak install -y flathub org.freedesktop.Sdk//24.08
            sudo flatpak install -y flathub org.freedesktop.Platform//24.08
            # make linux-flatpak
        # - name: Upload the build
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: docker_gui(debug)
        #     path: build/docker/bombsquad_gui_debug_docker.tar
        # - name: Push to github image repository
        #   run: |
        #     docker tag bombsquad_gui_debug:latest ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_gui:debug_nightly_x86_64
        #     docker push ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_gui:debug_nightly_x86_64

    # make_docker_server_debug_image:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - uses: actions/checkout@v4
    #     - name: Set up Python
    #       uses: actions/setup-python@v5
    #       with:
    #         python-version: '3.13'
    #     - name: Setup project environment
    #       run: make env
    #     - name: Docker login
    #       uses: docker/login-action@v3
    #       with:
    #         registry: ghcr.io
    #         username: ${{ github.repository_owner }}
    #         password: ${{ secrets.GITHUB_TOKEN }} 
    #     - name: Make the build
    #       run: |
    #         make docker-server-debug
    #         make docker-save
    #     - name: Upload the build
    #       uses: actions/upload-artifact@v4
    #       with:
    #         name: docker_server(debug)
    #         path: build/docker/bombsquad_server_debug_docker.tar
    #     - name: Push to github image repository
    #       run: |
    #         docker tag bombsquad_server_debug:latest ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:debug_nightly_x86_64
    #         docker push ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:debug_nightly_x86_64
            
    # make_docs:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - uses: actions/checkout@v4
    #     - name: Set up Python
    #       uses: actions/setup-python@v5
    #       with:
    #         python-version: '3.13'
    #     - name: Setup project environment
    #       run: make env
    #     - name: Make the build
    #       run: make docs
    #     - name: Upload the build
    #       uses: actions/upload-artifact@v4
    #       with:
    #         name: html_docs
    #         path: build/docs
