name: Test
on:
    push:
    workflow_dispatch:

jobs:
    make_flatpak_gui_debug:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Cache Python virtualenv
          id: cache-venv
          uses: actions/cache@v4
          env:
            cache-name: cache-python-dependencies
          with:
            path: .venv # cache the virtualenv directory
            key: ${{ runner.os }}-venv-${{ env.cache-name }}-${{ hashFiles('config/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-venv-${{ env.cache-name }}-
              ${{ runner.os }}-venv-
        - name: Cache Flatpak builder repo
          id: cache-flatpak-repo
          uses: actions/cache@v4
          with:
            path: cache/flatpak/repo
            key: ${{ runner.os }}-flatpak-repo-${{ hashFiles('config/flatpak/net.froemling.BombSquad.yml') }}
            restore-keys: |
              ${{ runner.os }}-flatpak-repo-
        - name: Cache Flatpak SDK and Platform
          id: cache-flatpak-sdk
          uses: actions/cache@v4
          with:
            path: ~/.local/share/flatpak
            key: ${{ runner.os }}-flatpak-sdk-${{ hashFiles('config/flatpak/net.froemling.BombSquad.yml') }}
            restore-keys: |
              ${{ runner.os }}-flatpak-sdk-
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'
        - name: Setup project environment
          run: |
            make env
        - name: Install dependencies
          run: |
            sudo apt install -y flatpak flatpak-builder
        # - name: Build Flatpak
        #   uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        #   with:
        #     bundle: bombsquad.flatpak
        #     manifest-path: config/flatpak/net.froemling.BombSquad.yml
        #     cache-key: flatpak-builder-${{ hashFiles('config/flatpak/net.froemling.BombSquad.yml') }}-${{ github.sha }}
        #     cache: true
        #     restore-cache: true
        #     repository-name: flathub
        #     repository-url: https://flathub.org/repo/flathub.flatpakrepo

        - name: Make the build
          run: |
            sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
            echo "remote added"
            sudo flatpak install -y flathub org.freedesktop.Sdk//24.08
            sudo flatpak install -y flathub org.freedesktop.Platform//24.08
            make linux-flatpak
        - name: Upload the build
          uses: actions/upload-artifact@v4
          with:
            name: bombsquad(debug).flatpak
            path: bombsquad.flatpak
     